[package]
name = "rustdoc"
version = "0.1.0"
authors = ["steveklabnik <steve@steveklabnik.com>"]
license = "MIT/Apache-2.0"

[[bin]]
name = "rustdoc"
doc = false

[dependencies]
rls-analysis = "0.4.0"
clap = "2.24.2"
jsonapi = "0.5.2"
serde_json = "0.9.10"
error-chain = "0.10.0"
indicatif = "0.6.0"

[build-dependencies]
lazy_static = "0.2.8"
walkdir = "1.0.7"
error-chain = "0.10.0"
